apiVersion: v1
kind: Pod
metadata:
  name: apache-webserver
spec:
  containers:
    - name: apache-webserver
      image: httpd:latest
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/local/apache2/htdocs"
          name: shared-data-pvc
  volumes:
    - name: shared-data-pvc
      persistentVolumeClaim:
        claimName: shared-data