apiVersion: v1
kind: Pod
metadata:
  name: nginx-webserver
spec:
  containers:
    - name: nginx-webserver
      image: nginx:latest
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: shared-data-pvc
  volumes:
    - name: shared-data-pvc
      persistentVolumeClaim:
        claimName: shared-data