apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: hello-from-pod
  name: hello-from-pod
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-from-pod
  type: LoadBalancer
status:
  loadBalancer: {}
